### ISSUE TITLE
fisherman.sh is no longer working

### ISSUE THREAD

**Issue by davo** [ellerbrock/fish-shell-setup-osx#7]
Here is the [Fisherman.sh whois](https://www.whois.com/whois/fisherman.sh). At first I thought it was a connectivity issue, but it seems like the domain expired.

**Comment by jorgebucaran** [comment]
@davo I ran out of money, so I took the site down. 😉 

---

Fisher's documentation can be consumed directly from the main repository: 
- <https://github.com/jorgebucaran/fisher>

For other resources see awesome fish
- <https://github.com/jorgebucaran/awesome-fish-shell>

**Comment by ellerbrock** [comment]
hi @jorgebucaran,

if you need a place to host your website let me know, i could help you with that.

**Comment by jorgebucaran** [comment]
It was an attempt at a joke. I did let the domain expire, but I took the site down because I didn't want to maintain it anymore. Your offer is very kind @ellerbrock, thank you. We're good to close here.
