### ISSUE TITLE
refactor: fisherman→fisher

### ISSUE THREAD

**Issue by jorgebucaran** [ellerbrock/fish-shell-setup-osx#9]
Hi @ellerbrock! Fisher is the continuation of and successor to Fisherman. Could you please rename your repository, tags, and mentions of ~~"fisherman"~~ and replace them with **"fisher"**?

About changing the name of the repository; it is safe to do it. When you rename a repository, username or organization account, old links redirect to the new location. Changing the name of your repository will not result in broken-links.

See: https://blog.github.com/2013-05-16-repository-redirects-are-here

Closes: #7

**Comment by jorgebucaran** [comment]
@ellerbrock Ping :) Do you need help with anything?

**Comment by ellerbrock** [comment]
hi @jorgebucaran, to be honest i move since quite a while to the zsh shell.
would you be so kind to make a pr with your changes?

**Comment by jorgebucaran** [comment]
@ellerbrock No, problem, but you'll have to change the labels and the name of the repository yourself, as those are changes that only an administrator can make. PRs are code only.


<img width="821" alt="screen shot 2018-10-26 at 20 05 14" src="https://user-images.githubusercontent.com/56996/47562834-d0502f00-d95a-11e8-9586-7d80ab69a3cb.png">

If you are not using fish-shell anymore, I suggest you archive this repository too. To do that, access the repository settings and click "Archive this repository".


<img width="781" alt="screen shot 2018-10-26 at 20 07 01" src="https://user-images.githubusercontent.com/56996/47562824-c5959a00-d95a-11e8-8ae3-a7dc4c940856.png">

**Comment by jorgebucaran** [comment]
Incoming PR _#10_  💨
